version: '3.8'

services:
  bot:
    image: bot_image
    build:
      context: .
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=1
      - DB_NAME=dombrobod_db
      - DB_PORT=5432
      - DB_HOST=postgres
    depends_on:
      - postgres
    networks:
      - my_network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=dombrobod_db
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
